// Code generated by map_generator — DO NOT EDIT BY HAND.
// 來源: map_generator /api/generate/game1?format=gofile&seed=g1-std
// 再生: 於 map_generator 啟動 API 後 curl 上述端點覆蓋本檔。
package game

// ---- 地圖 (三段式: 地上 / 地下層 / 月之裏側) ----
var mapRows = []string{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TT___,_T_____,T____,________T___T__T__________________TT",
	"TT_TTT______,TT_T____TTT_TT_T_________T____T_TTT_____TTT",
	"TT_TT___TT_,____ZZZZZZZZZZZZZZZZZZZZZZZZ____TTT__T_TT_TT",
	"TTT_TT____T_T_T_ZqqqqqqqqqqqqqqqqqqqqqqZT__T__T_TT_T__TT",
	"TT___TT________TZqqqqqqqqqqMMqqqqqqqqqqZ___T_________TTT",
	"TT_______T__T___ZqqZqqqqqqqqqqqqqqqqZqqZ_____T__T_TT__TT",
	"TT___T___T_T___TZqqqqqqqqqqqqqqqqqqqqqqZT_,_T____T__T_TT",
	"TT_T__TT________Zqqqqqqqqqqqqqqqqq>qqqqZ__T____T_____TTT",
	"TT__T__T_TTT_TT_ZqqZqqqqqqqqqqqqqqqqZqqZT__T_TT__T____TT",
	"TT__T__T________ZqqqqqqqqqqqqqqqqqqqqqqZ_TT_T___T_TT__TT",
	"TT_TT__kkkkkkkkTZqqqqqqqqqqqqqqqqqqqqqqZ_____T____T_TTTT",
	"TT___T_kkkkkkkkTZZZZZZZZZZZqqZZZZZZZZZZZ__kkkkkkkkT___TT",
	"TT_TT__kkkkkkkk_____TT__T__PP_T___TT__T__Tkkkkkkkk__TTTT",
	"TTT__T_kkkkkkkk__TT__TT__T_PP________TT_T_kkkkkkkk_T__TT",
	"TT__TT__kkkkkkkT_T____T__o_PPTo___T___T__Tkkkkkkkk___TTT",
	"TT__T_TTkkkkkkkT____T___T__PP_T_T___T_T__T___T__T_T___TT",
	"TTT___,_kkkkkkkTT_T__TT_T__PP_TT_______T_T____TT______TT",
	"TT__T__T______T__________T,PPT__T_T_T_T_TTT___T_TTTT__TT",
	"TT_T__TTT___TTTT_T___T___o_PP_o___T_____TT______,_T___TT",
	"TT_TT_T___T_________T__T___PP_T_T____T____________TT__TT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TT...........g...........g.PP.................r.....g.TT",
	"TT......g....g..gg.........PP.........g.....g.,g......TT",
	"TT.g......gg......g.,....g.PP..g..g......r...g.g....ggTT",
	"TT.....,...r...g...g.......PP......g........g.........TT",
	"TT..g.FFFFFFFFFFFFFFFFFFFFFPPFFFFFFFFFFFFFFFFFFFFF....TT",
	"TT....F........gg,g...g....PPg.............g...ggF....TT",
	"TT....F..........g.........PP..g.................F...,TT",
	"TT....Fg.RRRRRRRRR......g.gPP....g....UUUUUUUUU..F.g..TT",
	"TT....F.gRRRRRRRRR......g..PP.r.......UUUUUUUUU..F....TT",
	"TT....F.gHHCCDCHHH..g...g.gPPg........HHAADAHHH..F....TT",
	"TT..,.Fg.g...p.............PP....g....g.g.p.g..g.F....TT",
	"TT..,.F................ggg.PP.........ggg...,...,Fg..gTT",
	"TT....F.g..............g.g.PP..g...g.............F...rTT",
	"TT....F.r..r.g.....gg......PP.......g.....,g..g.,Fg.g.TT",
	"TT....F.,VVVVVVVVV.g.......PP.........RRRRRRRRR..F..g.TT",
	"TT....F..VVVVVVVVV...,..LppppppL......RRRRRRRRR..F....TT",
	"TT.,..F.gHHHHDHHHH.rg...pppppppp......HHHHDHHHH..F.g..TT",
	"TT.g..F...g..p..........pppppppp.g........p.,...gF....TT",
	"TTg...FPPPPPPPPPPPPPPPPPpOppppppPPPPPPPPPPPPPPPPPFg...TT",
	"TT....F...g....g......ggppppppppg.......r.......rF....TT",
	"TT....F...........,.....LppppppLgg...g......g....F....TT",
	"TT....F.........g,....g...gPP,.g......g.......,..F....TT",
	"TTgg..F.g...........g......PP....................F.,..TT",
	"TT...gF...g....g.....g.....PP.g.........gg..g....F,...TT",
	"TT...gF.,..........g.g..g..PP...x.g.,..g..ggg....F....TT",
	"TT....F.g........,.........PP...ffffffffff.g.....F.g.gTT",
	"TT....F........r.......g..gPP...ffffffffff.....ggF....TT",
	"TT.g..F....................PP..gffffffffffg.g....F...gTT",
	"TT..,gF...,..............g.PP...ffffffffffg.g..ggF....TT",
	"TT....Fg......g..g......g..PP...g................Fg...TT",
	"TT..g.F..g..............g..PP.........g..........F...,TT",
	"TT....FFFFFFFFFFFFFFFFFFFFFPPFFFFFFFFFFFFFFFFFFFFF....TT",
	"TT...gg.............g...g.SPPg.......g..g........gr...TT",
	"TT.....................,...PP..........g...g..g.......TT",
	"TT........g......g.........PP.....,.g....g...gg.......TT",
	"TT.g....................g..PP.g.......gggg.......r....TT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"cccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
	"cccccccccccccccccccccccccccccccdccccccccccccccccddcccccc",
	"ccccccdddddoddccddccccccdddcccdddccccccddccccccddddccccc",
	"cccccdddddddddddddddccccdlddddddddccccdddddccccddddddmcc",
	"cccclllllddddddddddGGdccllllddddddddcdddddddcccddddddddc",
	"ccclllllllddddddddd@ddlcccllldddddddddddddddcccdddddddcc",
	"ccdllllllldddcddddddddllcccllldddddddddddddddcddddddddcc",
	"cddddddddddddddddddlddddddddddldddddddddddddddddddddddcc",
	"cddlllllllddddddddllldllllllldddddddddddddddddddddddddcc",
	"cmdllcllllddddddddddddllllllllldddddddddddddddddddddddcc",
	"ccdmccclldddmccdddllldllllllllddddddddddddddddddddddddcc",
	"ccccctddddddccccdddlddccllllddddddddddddddddddddddddddmc",
	"cccccddd<ddcccccdddddccccldddddddddddddddddddddddddddddc",
	"cccccdd^dddcccccdddddccccdddddddddddddddddcccodddddddddc",
	"cccccdAdAddcccccdddddccccmddddddddddddcdddccccddddddddcc",
	"ccccdddddxddccccdddddcccccdddddddddddcccdddccccdddddddcc",
	"cccddddddddddcccddddcccccccddddddddddccddddmccccddddddcc",
	"cccddddddddddcccddddcccccccddddddddddccdddddccccdddddccc",
	"ccddddddddddddddddddcccccccddddddddddcccddddcccdddddcccc",
	"cdddddddddddddddddddmcccccccccdddddddccccddcccdddddccccc",
	"cdddddddddddddddddddddccccccccccccddcccccccccccddccccccc",
	"cdddddddddddddmdccdddccccccccccccccccccccccccccccccccccc",
	"ccddccddcccccccccccccccccccccccccccccccccccccccccccccccc",
	"cccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnn@nnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvvvvvvvv:vvvvvvvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnn:::::::::::::::::::vvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvvvvvvvv:vvvv:vvvvvvvvvvvvvvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvvvvvvvv:vvvv:nnnnnnnnnnnnnvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvnnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvnnnnnnnnnnnnnvvvvvvn*nnnnnAnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvv:vvvvvvvvvvvvnnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvv:::::::::::::nnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnnnnnnnnnnnnnnnnvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnn*nnnnnnnnnnnnnvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnnnnEEEEEnnnnn*nvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnnnnnnnvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnn*nvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvnnnnnnnnnnnvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
	"vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
}

// 層級界線 (row)
const (
	dungeonTopRow = 64 // 地下層
	voidTopRow    = 88 // 月之裏側
)

// 階梯傳送對 (落點錯開一格避免來回彈跳)
var (
	StairsDownTile = [2]int{34, 9}
	StairsUpTile   = [2]int{8, 76}
	StairsDownLand = [2]int{8, 77}
	StairsUpLand   = [2]int{34, 10}
)

// Portals 全地圖傳送點 (階梯 + 深淵之門 ↔ 月之裏側)
var Portals = []Portal{
	{From: StairsDownTile, To: StairsDownLand},
	{From: StairsUpTile, To: StairsUpLand},
	{From: [2]int{19, 69}, To: [2]int{28, 94}, MinQuest: 14, Deny: "深淵之門緊閉——先向村長羅文回報封印成果。"},
	{From: [2]int{28, 93}, To: [2]int{19, 70}},
}

// 劇情觸發區 (抵達判定)
var ShrineGate = Rect{X1: 25, Y1: 14, X2: 30, Y2: 15}
var AbyssGate = Rect{X1: 17, Y1: 69, X2: 22, Y2: 70}
var CoreAltar = Rect{X1: 24, Y1: 113, X2: 32, Y2: 114}

// 安全區 (怪物禁入 + 玩家回血) 與重生 tile
var genSafes = []Rect{
	Rect{X1: 7, Y1: 31, X2: 48, Y2: 56},
	Rect{X1: 5, Y1: 75, X2: 9, Y2: 79},
	Rect{X1: 26, Y1: 92, X2: 30, Y2: 94},
	Rect{X1: 26, Y1: 102, X2: 30, Y2: 106},
}

var genSpawnTile = [2]int{27, 44}

// DefaultSpawnAreas 生怪區 (由地圖 zone 掃描生成; Floor 0 = 草叢 tallgrass)
func DefaultSpawnAreas() []SpawnArea {
	return []SpawnArea{
		{Region: Rect{3, 26, 53, 29}, Kind: "wolf", Count: 4}, // fieldNorth
		{Region: Rect{2, 30, 5, 56}, Kind: "slime", Count: 6}, // fieldWest
		{Region: Rect{50, 33, 53, 55}, Kind: "beetle", Count: 5}, // fieldEast
		{Region: Rect{3, 58, 49, 61}, Kind: "slime", Count: 3}, // fieldSouth
		{Region: Rect{3, 58, 49, 61}, Kind: "beetle", Count: 3}, // fieldSouth
		{Region: Rect{7, 12, 14, 18}, Kind: "wolf", Count: 2}, // forestWest
		{Region: Rect{7, 12, 14, 18}, Kind: "wolf_king", Count: 1}, // forestWest
		{Region: Rect{42, 13, 49, 16}, Kind: "wolf", Count: 3}, // forestEast
		{Region: Rect{17, 5, 38, 13}, Kind: "slime_king", Count: 1, Floor: 'q'}, // templeHall
		{Region: Rect{1, 65, 54, 71}, Kind: "shade", Count: 3, Floor: 'd'}, // dungeonUpper
		{Region: Rect{1, 72, 54, 79}, Kind: "shade", Count: 2, Floor: 'd'}, // dungeonMid
		{Region: Rect{1, 72, 54, 79}, Kind: "gargoyle", Count: 2, Floor: 'd'}, // dungeonMid
		{Region: Rect{1, 80, 53, 86}, Kind: "eclipse_golem", Count: 1, Floor: 'd'}, // dungeonDeep
		{Region: Rect{2, 88, 33, 97}, Kind: "wraith", Count: 3, Floor: 'n'}, // voidUpper
		{Region: Rect{2, 98, 46, 108}, Kind: "wraith", Count: 2, Floor: 'n'}, // voidMid
		{Region: Rect{2, 98, 46, 108}, Kind: "sentinel", Count: 2, Floor: 'n'}, // voidMid
		{Region: Rect{21, 109, 46, 116}, Kind: "sentinel", Count: 2, Floor: 'n'}, // voidLower
		{Region: Rect{22, 110, 34, 115}, Kind: "eclipse_core", Count: 1, Floor: 'n'}, // voidCore
	}
}

// NPC 落點 tile (story.go 據此擺放村長/鐵匠)
var genNPCTiles = map[string][2]int{
	"elder": {25, 45},
	"smith": {13, 44},
}
